name: hopperstudios
description: the official hopper studios app for windows and mobile

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  cloud_firestore: 5.4.4
  cloud_firestore_platform_interface: 6.4.3
  cloud_firestore_web: 4.3.2
  cloud_functions: 5.1.3
  cloud_functions_platform_interface: 5.5.37
  cloud_functions_web: 4.10.2
  collection: 1.18.0
  firebase_analytics: 11.3.3
  firebase_analytics_platform_interface: 4.2.5
  firebase_analytics_web: 0.5.10+2
  firebase_auth: 5.3.1
  firebase_auth_platform_interface: 7.4.7
  firebase_auth_web: 5.13.2
  firebase_core: 3.6.0
  firebase_core_platform_interface: 5.3.0
  firebase_core_web: 2.18.1
  firebase_crashlytics: 4.1.3
  firebase_crashlytics_platform_interface: 3.6.44
  firebase_performance: 0.10.0+8
  firebase_performance_platform_interface: 0.1.4+44
  firebase_performance_web: 0.1.7+2
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  flutter_stripe: 11.1.0
  flutter_stripe_web: 6.1.0
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  google_sign_in: 6.2.1
  google_sign_in_android: 6.1.30
  google_sign_in_ios: 5.7.7
  google_sign_in_platform_interface: 2.4.5
  google_sign_in_web: 0.12.4+2
  intl: 0.19.0
  json_path: 0.7.2
  page_transition: 2.1.0
  path_provider: 2.1.4
  path_provider_android: 2.2.10
  path_provider_foundation: 2.4.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  plugin_platform_interface: 2.1.8
  provider: 6.1.2
  rxdart: 0.27.7
  shared_preferences: 2.3.2
  shared_preferences_android: 2.3.2
  shared_preferences_foundation: 2.5.2
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.2
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: 6.1.2
  sign_in_with_apple_platform_interface: 1.1.0
  sign_in_with_apple_web: 2.1.0
  sqflite: 2.3.3+1
  sqflite_common: 2.5.4+3
  stream_transform: 2.1.0
  stripe_android: 11.1.0
  stripe_ios: 11.1.0
  stripe_js: 6.1.0
  stripe_platform_interface: 11.1.1
  timeago: 3.6.1
  url_launcher: 6.3.0
  url_launcher_android: 6.3.10
  url_launcher_ios: 6.3.1
  url_launcher_linux: 3.2.0
  url_launcher_macos: 3.2.1
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.3.3
  url_launcher_windows: 3.1.2

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
  
